### ISSUE TITLE
数据文件不完整，实验复现不了。

### ISSUE THREAD

**Issue by Ysis0** [XinPeng97/TNNLS_DCLN#1]
作者，你好！我在复现您的论文是遇到了这个错误**FileNotFoundError: [Errno 2] No such file or directory: 'data/cora/diff.npy'**，缺少部分数据文件，请问您能提供完整的数据文件吗》

**Comment by XinPeng97** [comment]
你可以删除data/cora文件夹，之后重新运行python main.py --dataset cora。
如果仍然报错，你可能需要在dataset.py文件的第51行和第69行后同时添加代码：
idx_train, idx_val, idx_test = np.squeeze(idx_train), np.squeeze(idx_val), np.squeeze(idx_test)

**Comment by XinPeng97** [comment]
> 作者，你好！我在复现您的论文是遇到了这个错误**FileNotFoundError: [Errno 2] No such file or directory: 'data/cora/diff.npy'**，缺少部分数据文件，请问您能提供完整的数据文件吗》

你可以删除data/cora文件夹，之后重新运行python main.py --dataset cora。
如果仍然报错，你可能需要在dataset.py文件的第51行和第69行后同时添加代码：
idx_train, idx_val, idx_test = np.squeeze(idx_train), np.squeeze(idx_val), np.squeeze(idx_test)

**Comment by Ysis0** [comment]
谢谢~
